/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/marcodamico/PhD/energy17/SLURM_SIMULATOR/install/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/home/marcodamico/PhD/energy17/SLURM_SIMULATOR/install/slurm_conf/slurm.conf";
char *default_plugstack = "/home/marcodamico/PhD/energy17/SLURM_SIMULATOR/install/slurm_conf/plugstack.conf";
