/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/home/bsc33/bsc33882/SIMULATOR_SLURM_JUELICH_GIT_TEST/install/slurm_varios/lib/slurm";
char *default_slurm_config_file = "/home/bsc33/bsc33882/SIMULATOR_SLURM_JUELICH_GIT_TEST/install/slurm_conf/slurm.conf";
char *default_plugstack = "/home/bsc33/bsc33882/SIMULATOR_SLURM_JUELICH_GIT_TEST/install/slurm_conf/plugstack.conf";
